eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    status-page-url-path: /swagger-ui.html#!

server:
  port: 8763

spring:
  application:
    name: scheduler

##datasource config
#jdbc:
#  driverClassName: com.mysql.jdbc.Driver
#  url: jdbc:mysql://192.168.153.129:3306/quartz?zeroDateTimeBehavior=convertToNull&amp;useUnicode=true&amp;characterEncoding=utf-8
#  username: root
#  password: 123456
#
##mybatis config
#mybatis:
#  typeAliasesPackage: com.exc.repository.mapper
#  mapperLocations: classpath*:com.exc.repository.mapper/*.xml